{% set name = "py-gfm" %}
{% set version = "1.0.0" %}
{% set sha256 = "e5805d2680791ee8b38fc846c650d6c812682c8b1a939a64c29618a1f701e093" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
requirements:
  host:
    - python
    - pip
  run:
    - python
    - markdown

test:
  imports:
    - gfm
    - mdx_gfm
    - mdx_partial_gfm


about:
  home: https://github.com/zopieux/py-gfm
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An implementation of Github-Flavored Markdown written as an extension to the Python Markdown library.
  description: |
    'An implementation of Github-Flavored Markdown written as an extension to the Python Markdown library.'
  dev_url: https://github.com/Zopieux/py-gfm

extra:
  recipe-maintainers:
    - williamjamir
    - nicoddemus
