travis:
  secure:
    BINSTAR_TOKEN: pjdwEsLlieMD3dtOTPeZZFDZ2vFVXvP2XkyrJ82iwYTfkFb8OE6YSCdZqRFM/89kKFeRMC1iikwmrLapRTG3yHEupxpGzCEuWVct8msfoTc3VBD80xrZm3YjxnTe3gkqqnr9P2XbSahgpF6VViwXVdx0KZjQGYlC+rntneT5sWbb4LKEG1Mrx5ygLCwA0W9bxlzt6Sr++GRC7ZP/+mSzX361s5/1Ca6fo0J0NSMaN8Kc/2jP1V7szD9B5mWKdIRlcvSuO1q4USWUwZndRZmHMwin5ScitFm4h+1Oi3kCmi51dAXCA0q+bzVNakN46ik/sGezZ9iaBsWoh8j8DsOkErR/DQpjKOe03C3LqXaxeq8nXH6Ab+2LYXH1W/IGVy4zbqeTnTRWmS8Zn+TaIJiApNWpJvAN6ttIw+gvhanfy4lzWpVoDPzmanbamxdrj7P2wIuioSHDYtjHp3NOKHO7qMa48ZLITHlxTb66+dUSQQExWQLjYVBkfU6wq8EWkHVNc/Dhq82xUytgouRyS7b8Fhkbs8ODV9Vgvt3cQ7JImpT8YMsHYTK0oeRHnIVxHZBYQfSzterAKA9mAOJ4IrP6Akchc0lb6+1WP3cJ6ySu7jR2q72+GzkMJ8S1Oo4Yd31pLfyq8kFpqKA1YWFBTjvvTkBRAxZ3p6lomAztk+L83s0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
